name: lazy_string
description: A new Flutter package project.
version: 0.0.2
author: Thit Lwin <thitlwincoder@gmail.com>
homepage: https://github.com/thitlwincoder/lazy_string

environment:
  sdk: ">=2.7.0 <3.0.0"
